### ISSUE TITLE
Expose vault service as NodePort does not work

### ISSUE THREAD

**Issue by ssubramanian123** [Boostport/kubernetes-vault#122]
Hi,
I have an usecase where kubedns is disabled using "DNSPolicy: Default" in all deployment. So Application should communicate either through NodePort or LoadBalancer. So Deployed vault svc as NodePort.

Before disabling kubedns, we used VAULT_ADDR as below

```
https://vault.vault:8200
```
Once kubedns is disbaled, I am trying to use the VAULT_ADDR as below
```
https://10.2.133.90:32029
```
But this endpoint is not working for vault-init   (https://github.com/Boostport/kubernetes-vault/tree/master/cmd/init)

Here is the Error

```
time="2018-04-26T22:07:22Z" level=fatal msg="Could not unwrap secret: unwrapped secret is empty. check whether the vault address is accessible from this pod and that the secret_id exists."
```

From other pods, I am able to hit the vault using nodeport IP as below
```
bash-4.2$ curl -k -X GET -H "X-Vault-Token: 28ae5a21-1d7b-aa0b-9e53-a788250a4367" 'https://10.2.133.90:32029/v1/auth/token/lookup-self'
{"request_id":"21d6706c-33ba-adcb-a172-cf2c957300e8","lease_id":"","renewable":false,"lease_duration":0,"data":{"accessor":"ccabe4f0-82d9-8ae4-1501-068b496c4379","creation_time":1523995133,"creation_ttl":0,"display_name":"root","entity_id":"","expire_time":null,"explicit_max_ttl":0,"id":"28ae5a21-1d7b-aa0b-9e53-a788250a4367","meta":null,"num_uses":0,"orphan":true,"path":"auth/token/root","policies":["root"],"ttl":0},"wrap_info":null,"warnings":null,"auth":null}
```

can anyone help me what I am missing here?

**Comment by F21** [comment]
Hey @ssubramanian123, can you post the contents of your `kubernetes-vault.yml`?

**Comment by ssubramanian123** [comment]
@F21 `kubernetes-vault` works fine. The issue is in vault-init. Here is our application deployment.yaml file.

In annotations has below entry

``` 
annotations:
        pod.boostport.com/vault-approle: specb_lrmedge
        pod.boostport.com/vault-init-container: install
```
init container has below entries

```
 initContainers:
      - env:
        - name: VAULT_ADDR
          value: https://10.2.133.90:32029
        - name: VAULT_SKIP_VERIFY
          value: "true"
        - name: VAULT_ROLE_ID
          value: "38fcbb1b-a140-a104-fa8e-c967d6a8424f"
        image: {{Our ECR Repo }}/vault-init:1.6.2
        imagePullPolicy: Always
        name: install
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/secrets/boostport.com
          name: vault-token
```

Here is the complete deployment.yaml

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: sharedlib
    env: dev
    role: service
  name: sharedlib
  namespace: specb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sharedlib
      env: dev
      role: service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        pod.boostport.com/vault-approle: specb_lrmedge
        pod.boostport.com/vault-init-container: install
      creationTimestamp: null
      labels:
        app: sharedlib
        env: dev
        role: service
      name: sharedlib
    spec:
      containers:
      - command:
        - /start.sh
        env:
        - name: DEPLOYMENT
          value: sharedlib
        - name: VAULT_ADDR
          value: https://10.2.133.90:32029
        - name: VAULT_SKIP_VERIFY
          value: "true"
        - name: MERGE_CONFIG_FILE
          value: "true"
        - name: CLOUD_ENVIRONMENT
          value: dev
        image: {{Our ECR Repo }}/k8s-config-middle:1.0.1
        imagePullPolicy: Always
        name: config-sidecar
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /kubernetes-vault
          name: kubernetes-vault
        - mountPath: /config-volume
          name: config-volume
        - mountPath: /shared-config-volume
          name: shared-config-volume
        - mountPath: /token
          name: vault-token   
      dnsPolicy: ClusterFirst
      initContainers:
      - env:
        - name: VAULT_ADDR
          value: https://10.2.133.90:32029
        - name: VAULT_SKIP_VERIFY
          value: "true"
        - name: VAULT_ROLE_ID
          value: "38fcbb1b-a140-a104-fa8e-c967d6a8424f"
        image: {{Our ECR Repo }}/vault-init:1.6.2
        imagePullPolicy: Always
        name: install
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/secrets/boostport.com
          name: vault-token
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: sa-lrmedge
      serviceAccountName: sa-lrmedge
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: app-volume 
      - emptyDir: {}
        name: vault-token
      - configMap:
          defaultMode: 420
          name: kubernetes-vault
        name: kubernetes-vault
      - emptyDir:
          medium: Memory
        name: config-volume

```

**Comment by F21** [comment]
@ssubramanian123 I can't find your `kubernetes-vault.yml` in the deployment. However, I believe this is due to your Vault TLS certificate. Kubernetes-Vault needs to have access to the CA certificate see https://github.com/Boostport/kubernetes-vault#vault-required. I see that you are using curl with the `-k` switch which allows insecure TLS connections. Does it still work if you remove `-k`?

**Comment by ssubramanian123** [comment]
@F21 Please find below complete kubernetes-vault.yaml file. I feel, If it is certificate issue then it will not work with VAULT_ADDR as "vault.vault:8200", but it works. When I am simply changing the address through nodeport then it does not work. not sure what is heppening here..

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-vault
  namespace: vault
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kubernetes-vault
  namespace: vault
rules:
- apiGroups: [""]
  resources:
  - pods
  verbs: ["list", "watch"]
- apiGroups: [""]
  resources:
  - endpoints
  verbs: ["get"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kubernetes-vault
subjects:
- kind: ServiceAccount
  name: kubernetes-vault
  namespace: vault
roleRef:
  kind: ClusterRole
  name: kubernetes-vault
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-vault
  namespace: vault
  labels:
    run: kubernetes-vault
spec:
  clusterIP: None
  selector:
    run: kubernetes-vault
  # Kubernetes-Vault does not need to expose any ports through a headless service.
  # However, there's a Kubernetes bug where the pods won't be registered in the API,
  # so we need to use this hack. See kubernetes/kubernetes#32796
  ports:
    - name: port
      port: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-vault
  namespace: vault
data:
  kubernetes-vault.yml: |-
    vault:
      addr: https://vault.vault:8200
      token: --K8S-VAULT-ROLE-ID--
      tls:
        caCert: /kubernetes-vault/ca.pem

    kubernetes:
      watchNamespace: ~^(default|vault|--WATCH-NAMESPACE--)$
      serviceNamespace: vault
      service: kubernetes-vault

    prometheus:
      tls:
        certFile: /kubernetes-vault/cert.pem
        certKey: /kubernetes-vault/cert.key
        caCert: /kubernetes-vault/ca.pem

  cert.pem: |-
      --K8-VAULT-CERT-PERM--

  cert.key: |-
      --K8-VAULT-CERT-KEY--

  ca.pem: |-
      --K8-VAULT-CA-PEM--
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubernetes-vault
  namespace: vault
spec:
  replicas: 3
  template:
    metadata:
      labels:
        run: kubernetes-vault
    spec:
      serviceAccountName: kubernetes-vault
      containers:
      - name: kubernetes-vault
        image: {ECRRepo}/kubernetes-vault:1.6.6
        imagePullPolicy: Always
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: config-volume
          mountPath: /kubernetes-vault
      volumes:
        - name: config-volume
          configMap:
            name: kubernetes-vault
```

**Comment by F21** [comment]
Try changing the vault section in your `kubernetes-vault.yml` to the following:

```yaml
  kubernetes-vault.yml: |-
    vault:
      addr: https://10.2.133.90:32029
```

**Comment by ssubramanian123** [comment]
@F21 I changed as you suggested. Now kubernetes-vault not able to connect to vault. Looks cert issue through node ip.
```
kubectl logs kubernetes-vault-6cc6ff586c-gmk95  -n vault
time="2018-04-27T16:04:27Z" level=debug msg="Discovered 3 nodes: [100.108.208.209 100.110.202.207 100.120.85.85]"
time="2018-04-27T16:04:27Z" level=fatal msg="Could not create the vault client: error parsing supplied token: failed to lookup Vault periodic token: Get https://10.2.133.90:32029/v1/auth/token/lookup-self: x509: cannot validate certificate for 10.2.133.90 because it doesn't contain any IP SANs"
```

**Comment by ssubramanian123** [comment]
I think i found the issue.. our cert is to connect using vault.vault but we are trying it with different endpoint so it is not working.. i will close this request, will re-open or create new ticket for other issues.

**Comment by F21** [comment]
From the error message, it looks like you just have to create a new cert for Vault. In the IP SAN for the vault certificate, include `10.2.133.90`. I think this should fix your problem.

**Comment by ssubramanian123** [comment]
@F21 instead of NodePort, If I enable the service as load balancer then I will have the URL as https://mydomain.net/v1/auth/token/lookup-self

During creation of open ssl certificate include this domain in the below files. Does this the change you are referring?


openssl.cnf
````
[req]
req_extensions = v3_req
distinguished_name = req_distinguished_name
[req_distinguished_name]
[ v3_req ]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
subjectAltName = @alt_names
[alt_names]
DNS.1 = vault
DNS.2 = vault.vault
DNS.3 = localhost
DNS.4 = mydomain.net
````

Please check and confirm.

**Comment by F21** [comment]
@ssubramanian123, yes that's correct. If you want to access Vault over TLS using its IP address, then the IP would need to be added as a subjectAltName.

**Comment by ssubramanian123** [comment]
@F21 Thanks for your input. Now I have added our DNS in subjectAltName.  Also updated kubernetes-vault.yaml with dns specific entry. Now kubernetes-vault comes up without any issue.  But application which uses init to connect with vault is not coming up. Looks still something is missing. Please find below the details.

kubernetes-vault.yaml
````
 kubernetes-vault.yml: |-
    vault:
      addr: https://mydomain.net:8200
      token: 8e97169f-0ea6-a1df-f82f-d7cd5e5edf25
      tls:
        caCert: /kubernetes-vault/ca.pem

    kubernetes:
      watchNamespace: ~^(default|vault|specb)$
      serviceNamespace: vault
      service: kubernetes-vault

    prometheus:
      tls:
        certFile: /kubernetes-vault/cert.pem
        certKey: /kubernetes-vault/cert.key
        caCert: /kubernetes-vault/ca.pem
kind: ConfigMap
metadata:
  name: kubernetes-vault
````
application pod install init container which mounts the token..

````
 initContainers:
      - env:
        - name: VAULT_ADDR
          value: https://10.2.133.90:32029
        - name: VAULT_SKIP_VERIFY
          value: "true"
        - name: VAULT_ROLE_ID
          value: "38fcbb1b-a140-a104-fa8e-c967d6a8424f"
        image: {{Our ECR Repo }}/vault-init:1.6.2
        imagePullPolicy: Always
        name: install
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/run/secrets/boostport.com
          name: vault-token
````

Error from above init container, it says it got timed out.

````
kubectl logs lrmedge-78d5c6fcc8-462dk  -n specb -c install -p
time="2018-05-02T22:02:52Z" level=fatal msg="Failed to create vault auth token because we timed out after 5m0s before receiving the secret_id. Exiting."
````



I am not sure what I am missing. If I simply change the vault ADDR to https://vault.vault:8200 then same deployment works fine.

Please help..
