### ISSUE TITLE
Could not create the vault client: validate certificate doesn't contain any IP SANs

### ISSUE THREAD

**Issue by Mar4eli** [Boostport/kubernetes-vault#126]
Good day!

First of all, thank you for project. We have tested it via quick start guide and in love with its potential.

I'm trying to befriend your project with our vault cluster and experince error, that can't fix.

We have vault cluster with 3 nodes joined by consul. They have additional vault_cluster_ip to communicate with current cluster leader. Vault cluster using https.

I have reproduced steps from guick start guide on our vault cluster and generated certificates. All certificates i leave on vault nodes.

From kubernetes host node i can get token via curl
```
curl -k -H "X-Vault-Token:  a2c939a0-875c-da10-8d2b-92aa22e45f64"  https://10.10.254.236:8200/v1/auth/token/lookup-self
```

I deploy kubernetes-vault pods and they are crashing. with message:
```
time="2018-06-29T09:39:26Z" level=debug msg="Discovered 0 nodes: []"
time="2018-06-29T09:39:27Z" level=fatal msg="Could not create the vault client: error parsing supplied token: failed to lookup Vault periodic token: Get https://10.10.254.249:8200/v1/auth/token/lookup-self: x509: cannot validate certificate for 10.10.254.249 because it doesn't contain any IP SANs
```

I'm using yor kubernetes-vault.yaml file, but change configmap for kubernetes-vault. Right now it looks like this:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-vault
data:
  kubernetes-vault.yml: |-
    vault:
      addr: https://vault_cluster_ip:8200
      token: a2c939a0-875c-da10-8d2b-92aa22e45f64
      tls:
        vaultCABackends:    
          - root-ca
    kubernetes:
      watchNamespace: ${KUBERNETES_NAMESPACE}
      serviceNamespace: ${KUBERNETES_NAMESPACE}
      service: kubernetes-vault
    prometheus:
      tls:
        vaultCertBackend: intermediate-ca
        vaultCertRole: kubernetes-vault
        vaultCABackends:
          - root-ca
```
i have tried several configurations for vaultCABackends, nothing seems to work.

I'm noob with certificates, but it seems strange for me that curl working and kubernetes-vault not. can you please tell me, what am i doing wrong?

**Comment by F21** [comment]
Can you check the certificates deployed for Vault? From the error message, it looks like you're telling Kubernetes-Vault cluster to access Vault using its IP address. However, the IP addresses are not set as SANs (subject alternative names) for the Vault certificates:

Try either of the following:
- Regenerate the Vault certificates and include their IP addresses as their SANs.
- Update your kubernetes-vault.yaml's vault.addr to access Vault using a hostname that is present in the Vault certificates' SAN.

The reason your `curl` works is because you are using `-k` which disables the verification of the certificate. If you remove the `-k` flag, it should also show a certification validation error.

**Comment by Mar4eli** [comment]
Thank you for reply!

I was able to successfully regenrate intermediate-ca with ip_sans. But can't regenerate root-ca in such way.

In kubernetes-vault.yaml what value should we use in parameter vaultCABackends for vault?
intermediate-ca? ip from ip_sans collection? or root_ca? hostname?

**Comment by F21** [comment]
You don't need to regenerate your Root CA. Your Root CA should not have any SANs, but the certificates issued by the Root CA should have the SANs set up correctly.

`vaultCABackends` should only be set if Vault is using itself as a certificate authority. It should point to one or more backends that are being used as a Root CA within Vault.

**Comment by Mar4eli** [comment]
> vaultCABackends should only be set if Vault is using itself as a certificate authority. It should point to one or more backends that are being used as a Root CA within Vault.

How should it point? should it be url? for example https://some_ip_or_dns:8200/v1/intermediate-ca
or should it be just an ip/dns name?

**Comment by F21** [comment]
It should not be a URL or IP. In your example, it should just be `intermediate-ca`. However, you should use the `root-ca` mount and not the `intermediate-ca` mount, because verification of the certificate requires the root CA certificate.

**Comment by Mar4eli** [comment]
Thank you for your patience and answers.

I have run out of ideas.

Intermediate Ca retifiacte has ip_sans:
```
Subject Alternative Names: IP Address:vault_cluster_ip, IP Address:vault1_up, IP Address:vault2_ip, IP Address:vault3_ip
```

kubernetes-vault.yaml has root-ca as vaultCABackends
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-vault
data:
  kubernetes-vault.yml: |-
    vault:
      addr: https://10.10.254.249:8200
      token: f2f69f2e-84a3-ea14-0a01-9471b2e145d9
      tls:
        vaultCABackends:
          - root-ca
    kubernetes:
      watchNamespace: ${KUBERNETES_NAMESPACE}
      serviceNamespace: ${KUBERNETES_NAMESPACE}
      service: kubernetes-vault
    prometheus:
      tls:
        vaultCertBackend: intermediate-ca
        vaultCertRole: kubernetes-vault
        vaultCABackends:
          - root-ca
```

Error is still the same
```
time="2018-06-29T12:00:35Z" level=debug msg="Discovered 0 nodes: []"
time="2018-06-29T12:00:35Z" level=fatal msg="Could not create the vault client: error parsing supplied token: failed to lookup Vault periodic token: Get https://vault_cluster_ip:8200/v1/auth/token/lookup-self: x509: cannot validate certificate for vault_cluster_ip because it doesn't contain any IP SANs"
```
