### ISSUE TITLE
Solved: Error from server (BadRequest): container "sample-app" in pod "sample-app-xxxxx" is waiting to start: PodInitializing

### ISSUE THREAD

**Issue by DrissiReda** [Boostport/kubernetes-vault#159]
I tried the quick start/deployment tutorial. I only installed k3s vault and jq, then I ran the `setup.sh`.

Both the vault and kubernetes-vault pods worked as expected, but the sample-app is stuck on `Init:0/1`.
Since I'm using k3s version 1.16.3 I had to switch the apiVersion to `apps/v1` and add the `selector: matchLabels` field with the same info as `metadata: labels`

My configuration 

<details>
<summary> vault.yaml </summary>

```yaml

apiVersion: v1
kind: Service
metadata:
  name: vault
  labels:
    app: vault
spec:
  ports:
    - name: vault
      port: 8200
  selector:
    app: vault
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vault
  name: vault
spec:
  selector:
    matchLabels:
      app: vault
  replicas: 1
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - image: vault
        name: vault
        ports:
        - containerPort: 8200
          name: vaultport
          protocol: TCP
        securityContext:
         capabilities:
           add:
             - IPC_LOCK
        env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: vault-root-token

```
</details>

<details>
<summary> kubernetes-vault.yaml</summary>

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-vault
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kubernetes-vault
rules:
- apiGroups: [""]
  resources:
  - pods
  verbs: ["list", "watch"]
- apiGroups: [""]
  resources:
  - endpoints
  verbs: ["get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kubernetes-vault
subjects:
- kind: ServiceAccount
  name: kubernetes-vault
  namespace: default
roleRef:
  kind: ClusterRole
  name: kubernetes-vault
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-vault
  labels:
    run: kubernetes-vault
spec:
  clusterIP: None
  selector:
    run: kubernetes-vault
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-vault
data:
  kubernetes-vault.yml: |-
    vault:
      addr: http://vault:8200
      token: s.sbDgo5kn16g5kumkWVvQJedS
    kubernetes:
      watchNamespace: ${KUBERNETES_NAMESPACE}
      serviceNamespace: ${KUBERNETES_NAMESPACE}
      service: kubernetes-vault
    prometheus:
      tls:
        vaultCertBackend: intermediate-ca
        vaultCertRole: kubernetes-vault
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-vault
  namespace: default
spec:
  replicas: 1 
  selector:
    matchLabels:
      run: kubernetes-vault
  template:
    metadata:
      labels:
        run: kubernetes-vault
    spec:
      serviceAccountName: kubernetes-vault
      containers:
      - name: kubernetes-vault
        image: boostport/kubernetes-vault
        imagePullPolicy: Always
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        volumeMounts:
        - name: config-volume
          mountPath: /kubernetes-vault
      volumes:
        - name: config-volume
          configMap:
            name: kubernetes-vault
```
</details>

<details>
<summary>sample-app.yaml </summary>

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
        app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
      annotations:
        pod.boostport.com/vault-approle: sample-app
        pod.boostport.com/vault-init-container: get-vault-token
    spec:
      containers:
      - name: sample-app
        image: boostport/kubernetes-vault-sample-app
        volumeMounts:
        - name: vault-token
          mountPath: /var/run/secrets/boostport.com
      initContainers:
      - name: get-vault-token
        image: boostport/kubernetes-vault-init
        imagePullPolicy: Always
        env:
        - name: VAULT_ROLE_ID
          value: 9995782b-9bc1-564a-e034-ac814fe5391c
        volumeMounts:
        - name: vault-token
          mountPath: /var/run/secrets/boostport.com
      volumes:
      - name: vault-token
        emptyDir: {}

```
</details>

Logs:

<details>
<summary>vault </summary>

```bash
==> Vault server configuration:

             Api Address: http://0.0.0.0:8200
                     Cgo: disabled
         Cluster Address: https://0.0.0.0:8201
              Listener 1: tcp (addr: "0.0.0.0:8200", cluster address: "0.0.0.0:8201", max_request_duration: "1m30s", max_request_size: "33554432", tls: "disabled")
               Log Level: info
                   Mlock: supported: true, enabled: false
           Recovery Mode: false
                 Storage: inmem
                 Version: Vault v1.3.0

WARNING! dev mode is enabled! In this mode, Vault runs entirely in-memory
and starts unsealed with a single unseal key. The root token is already
authenticated to the CLI, so you can immediately begin using Vault.

You may need to set the following environment variable:

    $ export VAULT_ADDR='http://0.0.0.0:8200'

The unseal key and root token are displayed below in case you want to
seal/unseal the Vault or re-authenticate.

Unseal Key: tKlelmusoxrFBA9dM4vcZOdZS9XcLc2NDohuCn/NDAs=
Root Token: vault-root-token

Development mode should NOT be used in production installations!

==> Vault server started! Log data will stream in below:

2019-12-17T09:48:11.859Z [INFO]  proxy environment: http_proxy= https_proxy= no_proxy=
2019-12-17T09:48:11.859Z [WARN]  no `api_addr` value specified in config or in VAULT_API_ADDR; falling back to detection if possible, but this value should be manually set
2019-12-17T09:48:11.860Z [ERROR] core: no seal config found, can't determine if legacy or new-style shamir
2019-12-17T09:48:11.860Z [ERROR] core: no seal config found, can't determine if legacy or new-style shamir
2019-12-17T09:48:11.860Z [INFO]  core: security barrier not initialized
2019-12-17T09:48:11.860Z [INFO]  core: security barrier initialized: stored=1 shares=1 threshold=1
2019-12-17T09:48:11.860Z [INFO]  core: post-unseal setup starting
2019-12-17T09:48:11.867Z [INFO]  core: loaded wrapping token key
2019-12-17T09:48:11.867Z [INFO]  core: successfully setup plugin catalog: plugin-directory=
2019-12-17T09:48:11.867Z [INFO]  core: no mounts; adding default mount table
2019-12-17T09:48:11.868Z [INFO]  core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2019-12-17T09:48:11.868Z [INFO]  core: successfully mounted backend: type=system path=sys/
2019-12-17T09:48:11.868Z [INFO]  core: successfully mounted backend: type=identity path=identity/
2019-12-17T09:48:11.869Z [INFO]  core: successfully enabled credential backend: type=token path=token/
2019-12-17T09:48:11.869Z [INFO]  core: restoring leases
2019-12-17T09:48:11.869Z [INFO]  rollback: starting rollback manager
2019-12-17T09:48:11.869Z [INFO]  expiration: lease restore complete
2019-12-17T09:48:11.870Z [INFO]  identity: entities restored
2019-12-17T09:48:11.870Z [INFO]  identity: groups restored
2019-12-17T09:48:11.870Z [INFO]  core: post-unseal setup complete
2019-12-17T09:48:11.870Z [INFO]  core: root token generated
2019-12-17T09:48:11.870Z [INFO]  core: pre-seal teardown starting
2019-12-17T09:48:11.870Z [INFO]  rollback: stopping rollback manager
2019-12-17T09:48:11.870Z [INFO]  core: pre-seal teardown complete
2019-12-17T09:48:11.870Z [ERROR] core: no seal config found, can't determine if legacy or new-style shamir
2019-12-17T09:48:11.870Z [INFO]  core.cluster-listener: starting listener: listener_address=0.0.0.0:8201
2019-12-17T09:48:11.871Z [INFO]  core.cluster-listener: serving cluster requests: cluster_listen_address=[::]:8201
2019-12-17T09:48:11.871Z [INFO]  core: post-unseal setup starting
2019-12-17T09:48:11.871Z [INFO]  core: loaded wrapping token key
2019-12-17T09:48:11.871Z [INFO]  core: successfully setup plugin catalog: plugin-directory=
2019-12-17T09:48:11.871Z [INFO]  core: successfully mounted backend: type=system path=sys/
2019-12-17T09:48:11.871Z [INFO]  core: successfully mounted backend: type=identity path=identity/
2019-12-17T09:48:11.871Z [INFO]  core: successfully mounted backend: type=cubbyhole path=cubbyhole/
2019-12-17T09:48:11.872Z [INFO]  core: successfully enabled credential backend: type=token path=token/
2019-12-17T09:48:11.872Z [INFO]  core: restoring leases
2019-12-17T09:48:11.872Z [INFO]  rollback: starting rollback manager
2019-12-17T09:48:11.872Z [INFO]  identity: entities restored
2019-12-17T09:48:11.872Z [INFO]  identity: groups restored
2019-12-17T09:48:11.872Z [INFO]  core: post-unseal setup complete
2019-12-17T09:48:11.872Z [INFO]  expiration: lease restore complete
2019-12-17T09:48:11.872Z [INFO]  core: vault is unsealed
2019-12-17T09:48:11.873Z [INFO]  expiration: revoked lease: lease_id=auth/token/root/he51a2b01946a72a4a417d655394c12f8a7c4dff79ad595838825d4639539898d
2019-12-17T09:48:11.874Z [INFO]  core: successful mount: namespace= path=secret/ type=kv
2019-12-17T09:48:11.884Z [INFO]  secrets.kv.kv_13e5160f: collecting keys to upgrade
2019-12-17T09:48:11.884Z [INFO]  secrets.kv.kv_13e5160f: done collecting keys: num_keys=1
2019-12-17T09:48:11.884Z [INFO]  secrets.kv.kv_13e5160f: upgrading keys finished
2019-12-17T09:48:16.038Z [INFO]  core: successful mount: namespace= path=root-ca/ type=pki
2019-12-17T09:48:16.239Z [INFO]  core: successful mount: namespace= path=intermediate-ca/ type=pki
2019-12-17T09:48:16.705Z [INFO]  core: enabled credential backend: path=approle/ type=approle

```
</details>

<details>
<summary> kubernetes-vault</summary>

```bash
time="2019-12-17T09:48:27Z" level=debug msg="Discovered 1 nodes: [10.42.0.10]"
time="2019-12-17T09:48:27Z" level=debug msg="2019/12/17 09:48:27 [INFO] serf: EventMemberJoin: 10.42.0.10:45678 10.42.0.10"
time="2019-12-17T09:48:27Z" level=debug msg="2019/12/17 09:48:27 [DEBUG] memberlist: Initiating push/pull sync with: 10.42.0.10:45678"
time="2019-12-17T09:48:27Z" level=debug msg="2019/12/17 09:48:27 [DEBUG] memberlist: Stream connection from=10.42.0.10:37550"
time="2019-12-17T09:48:27Z" level=debug msg="2019/12/17 09:48:27 [INFO] raft: Node at 10.42.0.10:45679 [Follower] entering Follower state (Leader: \"\")"
time="2019-12-17T09:48:29Z" level=debug msg="2019/12/17 09:48:29 [WARN] raft: Heartbeat timeout from \"\" reached, starting election"
time="2019-12-17T09:48:29Z" level=debug msg="2019/12/17 09:48:29 [INFO] raft: Node at 10.42.0.10:45679 [Candidate] entering Candidate state"
time="2019-12-17T09:48:29Z" level=debug msg="2019/12/17 09:48:29 [DEBUG] raft: Votes needed: 1"
time="2019-12-17T09:48:29Z" level=debug msg="2019/12/17 09:48:29 [DEBUG] raft: Vote granted from 10.42.0.10:45679. Tally: 1"
time="2019-12-17T09:48:29Z" level=debug msg="2019/12/17 09:48:29 [INFO] raft: Election won. Tally: 1"
time="2019-12-17T09:48:29Z" level=debug msg="2019/12/17 09:48:29 [INFO] raft: Node at 10.42.0.10:45679 [Leader] entering Leader state"
time="2019-12-17T09:48:29Z" level=debug msg="2019/12/17 09:48:29 [DEBUG] raft: Node 10.42.0.10:45679 updated peer set (2): [10.42.0.10:45679]"
time="2019-12-17T09:48:29Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T09:48:29Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T09:48:49Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T09:48:49Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T09:49:09Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T09:49:09Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T09:49:29Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T09:49:29Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T09:49:49Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T09:49:49Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T09:50:09Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T09:50:09Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T09:50:29Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T09:50:29Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T09:50:49Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T09:50:49Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T09:51:09Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T09:51:09Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T09:51:29Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T09:51:29Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T09:51:49Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T09:51:49Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T09:52:09Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T09:52:09Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T09:52:29Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T09:52:29Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T09:52:49Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T09:52:49Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T09:53:09Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T09:53:09Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T09:53:29Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T09:53:29Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T09:53:49Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T09:53:49Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T09:54:09Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T09:54:09Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T09:54:29Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T09:54:29Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T09:54:49Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T09:54:49Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T09:55:09Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T09:55:09Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T09:55:29Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T09:55:29Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T09:55:49Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T09:55:49Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T09:56:09Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T09:56:09Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T09:56:29Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T09:56:29Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T09:56:49Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T09:56:49Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T09:57:09Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T09:57:09Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T09:57:29Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T09:57:29Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T09:57:49Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T09:57:49Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T09:58:09Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T09:58:09Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T09:58:49Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T09:58:49Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T09:59:09Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T09:59:09Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T09:59:29Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T09:59:29Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T09:59:49Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T09:59:49Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T10:00:09Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T10:00:09Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T10:00:29Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T10:00:29Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T10:00:49Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T10:00:49Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T10:01:09Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T10:01:09Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"
time="2019-12-17T10:01:29Z" level=debug msg="Attempting to push wrapped secret_id to pod (sample-app-64dd74b88b-psg26)."
time="2019-12-17T10:01:29Z" level=error msg="Could not get secret_id for role (sample-app) for pod (sample-app-64dd74b88b-psg26): could not get secret_id: Error making API request.\n\nURL: PUT http://vault:8200/v1/auth/approle/role/sample-app/secret-id\nCode: 403. Errors:\n\n* 1 error occurred:\n\t* permission denied\n\n"

```
</details>

<details>
<summary>sample-app </summary>

```bash
Error from server (BadRequest): container "sample-app" in pod "sample-app-64dd74b88b-psg26" is waiting to start: PodInitializing

```
</details>
