### ISSUE TITLE
I added kubernetes-vault support to vault-sidekick.

### ISSUE THREAD

**Issue by darron** [Boostport/kubernetes-vault#49]
https://github.com/UKHomeOffice/vault-sidekick

Now it can read the JSON that kubernetes-vault outputs to grab secrets from Vault.

Here was the PR:

https://github.com/UKHomeOffice/vault-sidekick/pull/39

As part of my deploy - here's how I run it:

```yaml
      - name: vault-sidekick
        image: docker.repo.goes.here/vault-sidekick:tag
        env:
          - name: AUTH_FILE
            value: /var/run/secrets/boostport.com/vault-token
          - name: AUTH_FORMAT
            value: kubernetes-vault
          - name: VAULT_ADDR
            value: "https://vault.address.goes.here"
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        args:
          - -cn=secret:secret/secret-name-goes-here:fmt=yaml
        imagePullPolicy: Always
        volumeMounts:
        - name: vault-token
          mountPath: /var/run/secrets/boostport.com
        - name: secrets
          mountPath: /etc/secrets
```

In the end - this picked up the JSON dropped in `/var/run/secrets/boostport.com/vault-token` by kubernetes-vault and saved the actual secret in `/etc/secrets` for another container.

It's not in a current release - but if you build from master it's available.

Just thought I'd let you know - it's pretty handy and makes getting secrets nice and simple.
