### ISSUE TITLE
How to configure Vault to use itself as root CA

### ISSUE THREAD

**Issue by JulianWei** [Boostport/kubernetes-vault#63]
Hi @F21, in the document, you mentioned users can configure Kubernetes-Vault as following if Vault is configured as CA.
```
vault:
  addr: http://vault:8200
  token: 91526d9b-4850-3405-02a8-aa29e74e17a5
  tls:
    **vaultCABackends**:
      - root-ca
```
Currently I am using a self signed cert that generated by openssl for Vault TLS. And enable pki backend at path root-ca, But when I give above configuration to Kubernetes-Vault, it complained 
```
level=fatal msg="Could not create the vault client: error parsing supplied token: failed to lookup Vault periodic token: Get https://vault:8200/v1/auth/token/lookup-self: x509: certificate signed by unknown authority
```
Can you show some light here about how to configure Vault to use itself as root CA?

**Comment by F21** [comment]
Hey @JulianWei ,

In the case where you use Vault itself as the root CA, you need to first set up the PKI backend in Vault, for example creating one called `root-ca`. You then generate a certificate using this PKI backend for Vault. For example, in your case, you would generate a certificate for the `common_name` `vault` and perhaps SANs of `vault.default`, etc depending on what namespace Vault is running in.

Once that's done, you need to put the key and certificate in a location that can be accessed by Vault, configure `tls_cert_file` and `tls_key_file` per the [documentation](https://www.vaultproject.io/docs/configuration/listener/tcp.html#tls_cert_file) and restart Vault.

All of the above requires manual intervention by an operator, but I think it would be a good idea to write an operator to automate it.

As for, Kubernetes-Vault, simply set `vault.tls` to a list of PKI backends used by Vault:

```
vault:
  addr: http://vault:8200
  token: 91526d9b-4850-3405-02a8-aa29e74e17a5
  tls:
    vaultCABackends:
      - root-ca
```

In this case, Kubernetes-Vault will first connect to Vault without verifying the certificate presented by Vault to grab the CA certificates. Once this is done, all connections to Vault will be verified using the CA certificates.

Let me know if that helps! 😄
