### ISSUE TITLE
Look up allowed namespaces before starting

### ISSUE THREAD

**Issue by F21** [Boostport/kubernetes-vault#66]
We recently added deployments demonstrating using RBAC to limit what Kubernetes-Vault can access in #64 and #65.

Currently, Kubernetes-Vault needs a `ClusterRole` and `ClusterRoleBinding` to `watch` and `list` pods in ALL namespaces. This is to support using regex to watch multiple namespaces.

There is a PR to add support that will allow a service account to look up its own permissions: https://github.com/kubernetes/kubernetes/pull/48051

Once this is implemented, the following can be implemented in Kubernetes-Vault:
- Check that we can get our configured `endpoint` for discovery.
- On start up, check which namespaces we can `list` and `watch`.
- If there are no namespaces we can `list` and `watch`, exit with error.
- List the namespaces we can `list` and `watch` and start the watch goroutine to watch these namespaces.

This will support the use-case where operators do not want to give a Kubernetes-Vault deployment access to all namespaces.

**Comment by alejandroEsc** [comment]
If I am reading this correctly, its very unlikely you will need to create this type of complexity in your code. Instead of creating a cluster-role, which allows you access resources in all namespaces you could just create a role. That will limit the scope of the app to a single namespace.

**Comment by F21** [comment]
I ran some experiments on a v1.7.0 test cluster with RBAC enabled yesterday.

These were the RBAC objects I tried:

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-vault
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kubernetes-vault
rules:
- apiGroups: [""]
  resources:
  - pods
  verbs: ["list", "watch"]
- apiGroups: [""]
  resources:
  - endpoints
  verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kubernetes-vault
  namespace: default
subjects:
- kind: ServiceAccount
  name: kubernetes-vault
  namespace: default
roleRef:
  kind: ClusterRole
  name: kubernetes-vault
  apiGroup: rbac.authorization.k8s.io
```

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubernetes-vault
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kubernetes-vault
  namespace: default
rules:
- apiGroups: [""]
  resources:
  - pods
  verbs: ["list", "watch"]
- apiGroups: [""]
  resources:
  - endpoints
  verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kubernetes-vault
  namespace: default
subjects:
- kind: ServiceAccount
  name: kubernetes-vault
  namespace: default
roleRef:
  kind: Role
  name: kubernetes-vault
  apiGroup: rbac.authorization.k8s.io
```
Unfortunately, when Kubernetes-Vaults attempts to start its watcher, it received a message from the Kubernetes API saying that it did not have permissions to watch on all namespaces.

Kubernetes-Vault logs this error:

```
time="2017-07-17T23:28:52Z" level=error msg="Could not list pods: could not list pods: decode error status: payload is not a kubernetes protobuf object" 
time="2017-07-17T23:28:52Z" level=error msg="Error watching pods: decode error status: payload is not a kubernetes protobuf object" 
time="2017-07-17T23:28:52Z" level=error msg="Error watching pods: decode error status: payload is not a kubernetes protobuf object" 
time="2017-07-17T23:28:53Z" level=error msg="Error watching pods: decode error status: payload is not a kubernetes protobuf object" 
time="2017-07-17T23:28:54Z" level=error msg="Error watching pods: decode error status: payload is not a kubernetes protobuf object" 
```

This is because the error is not returned as a protobuf object, but after decoding it, the error is regarding not having permissions to watch all namespaces.

This is because Kubernetes-Vault uses `GET /api/v1/watch/pods`, see: https://kubernetes.io/docs/api-reference/v1.7/#watch-list-all-namespaces-66

However, if we restrict a `ClusterRole` to a namespace using `RoleBinding` or a `Role` and a `RoleBinding`, it uses this: `GET /api/v1/watch/namespaces/{namespace}/pods/{name}`. See https://kubernetes.io/docs/api-reference/v1.7/#watch-64

Therefore, in this case, I think we will need to look up what namespaces we can `list` and `watch`, and if it is not all namespaces, watch using `/api/v1/watch/namespaces/{namespace}/pods/{name}`.
