### ISSUE TITLE
role with a policy ... start container is not starting up

### ISSUE THREAD

**Issue by ssinhas** [Boostport/kubernetes-vault#93]
I have created a role 

vault write auth/approle/role/ms-templates secret_id_ttl=90s period=6h secret_id_num_uses=1 policies=ms-templates

now when I start a service with that role, start container is failing...

Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"lmms-dev","name":"ms-test-service-4280997542","uid":"d51e60a2-bf47-11e7-86cc-4201...
                pod.alpha.kubernetes.io/init-container-statuses=[{"name":"get-vault-token","state":{"running":{"startedAt":"2017-11-01T21:47:34Z"}},"lastState":{"terminated":{"exitCode":1,"reason":"Error","startedAt"...
                pod.alpha.kubernetes.io/init-containers=[{"name":"get-vault-token","image":"boostport/kubernetes-vault-init","env":[{"name":"VAULT_ROLE_ID","value":"1656077a-ee7b-a6b5-9c01-c37f19ae4515"}],"resources"...
                pod.beta.kubernetes.io/init-container-statuses=[{"name":"get-vault-token","state":{"running":{"startedAt":"2017-11-01T21:47:34Z"}},"lastState":{"terminated":{"exitCode":1,"reason":"Error","startedAt":...
                pod.beta.kubernetes.io/init-containers=[{"name":"get-vault-token","image":"boostport/kubernetes-vault-init","env":[{"name":"VAULT_ROLE_ID","value":"1656077a-ee7b-a6b5-9c01-c37f19ae4515"}],"resources":...
                pod.boostport.com/vault-approle=ms-templates
                pod.boostport.com/vault-init-container=get-vault-token
Status:         Pending
IP:             10.20.1.98

Events:
  Type     Reason                 Age                From                                                Message
  ----     ------                 ----               ----                                                -------
  Normal   Scheduled              47m                default-scheduler                                   Successfully assigned ms-test-service-4280997542-09zxk to gke-scribe-dev-default-pool-bee7c341-s3hm
  Normal   SuccessfulMountVolume  47m                kubelet, gke-scribe-dev-default-pool-bee7c341-s3hm  MountVolume.SetUp succeeded for volume "vault-token"
  Normal   SuccessfulMountVolume  47m                kubelet, gke-scribe-dev-default-pool-bee7c341-s3hm  MountVolume.SetUp succeeded for volume "cloudsql"
  Normal   SuccessfulMountVolume  47m                kubelet, gke-scribe-dev-default-pool-bee7c341-s3hm  MountVolume.SetUp succeeded for volume "secrets"
  Normal   SuccessfulMountVolume  47m                kubelet, gke-scribe-dev-default-pool-bee7c341-s3hm  MountVolume.SetUp succeeded for volume "default-token-s39v8"
  Warning  BackOff                1m (x61 over 37m)  kubelet, gke-scribe-dev-default-pool-bee7c341-s3hm  Back-off restarting failed container
  Normal   Pulling                1m (x8 over 47m)   kubelet, gke-scribe-dev-default-pool-bee7c341-s3hm  pulling image "boostport/kubernetes-vault-init"
  Normal   Pulled                 1m (x8 over 47m)   kubelet, gke-scribe-dev-default-pool-bee7c341-s3hm  Successfully pulled image "boostport/kubernetes-vault-init"
  Normal   Created                1m (x8 over 47m)   kubelet, gke-scribe-dev-default-pool-bee7c341-s3hm  Created container
  Normal   Started                1m (x8 over 47m)   kubelet, gke-scribe-dev-default-pool-bee7c341-s3hm  Started container
  Warning  FailedSync             1m (x68 over 42m)  kubelet, gke-scribe-dev-default-pool-bee7c341-s3hm  Error syncing pod

Sample app i am able to deploy.. No issue there.  I don't see any logs.. How can I debug more?

**Comment by F21** [comment]
See if you can [get the logs from the init container](https://kubernetes.io/docs/tasks/debug-application-cluster/debug-init-containers/#accessing-logs-from-init-containers):

```
kubectl logs <pod-name> -c <init-container-name>
```

**Comment by ssinhas** [comment]
yes.. tried that.. no  logs

**Comment by F21** [comment]
Which version of k8s?

**Comment by ssinhas** [comment]
1.7.6..  Sample app i am able to  deploy... Only difference this  role has different policy..

**Comment by F21** [comment]
Can you post your deployment as well as the policy?

**Comment by ssinhas** [comment]
```yaml
# Source: ms-templates/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ms-test-service
  namespace: lmms-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-test-service
        chart: ms-templates-1.1.0
        release: ms-test-service
        heritage: Tiller
      annotations:
        pod.boostport.com/vault-approle: ms-templates
        pod.boostport.com/vault-init-container: get-vault-token
    spec:
      containers:
      - name: ms-test-service
        image: gcr.io/dev-lm/templates:4.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 10001
        volumeMounts:
        - name: vault-token
          mountPath: /var/run/secrets/boostport.com
        - name: secrets
          mountPath: /etc/secretspath
          readOnly: true
      initContainers:
      - name: get-vault-token
        image: boostport/kubernetes-vault-init
        imagePullPolicy: Always
        env:
        - name: VAULT_ROLE_ID
          value: 1656077a-ee7b-a6b5-9c01-c37f19ae4515
        volumeMounts:
        - name: vault-token
         mountPath: /var/run/secrets/boostport.com
      volumes:
      - name: secrets
        secret:
          secretName: google-services-secret
      - name: cloudsql
        emptyDir:
      - name: vault-token
        emptyDir: {}
      imagePullSecrets:
        - name: gcr-json-key
```

policy
```hcl
path "auth/approle/role/ms-templates/secret-id" {
  capabilities = ["update"]
}
path "secret/backend/*" {
  capabilities = ["read"]
}
```
